package edu.sit.signal.feedback;

import edu.sit.signal.apis.DbApis;
import edu.sit.signal.models.Feedback;
import java.io.IOException;
import java.io.PrintWriter;
import javax.servlet.ServletException;
import javax.servlet.annotation.WebServlet;
import javax.servlet.http.HttpServlet;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 *
 * @author Suthat
 */
@WebServlet(name = "AckApis", urlPatterns = {"/ack-apis"})
public class AckApis extends HttpServlet {

    /**
     * Processes requests for both HTTP
     * <code>GET</code> and
     * <code>POST</code> methods.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    protected void processRequest(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        
        // uuid generated by Signal client libraries and/or a device uuid
        String receiver = ""; //request.getParameter("receiver");
        
        String code = request.getParameter("code");
        String token = request.getParameter("token");
        String fbref = request.getParameter("fbref");
        String platform = request.getParameter("platform");
        String callback = request.getParameter("callback");
        
        response.setContentType("application/json;charset=UTF-8");
        PrintWriter out = response.getWriter();
        
        DbApis dbApis = new DbApis();
        dbApis.connect();
        
        try {
            
            if(code != null && token != null && fbref != null){
                
                boolean accepted = dbApis.getFbOTP(code, token, fbref);
                
                if(accepted){
                    // force check a NULL platform
                    try{
                        if(platform.equals("SIGNAL"));
                    }catch(Exception e){
                        platform = "N/A";
                    }
                    String referrer = request.getRemoteAddr() + " / " + request.getRemoteHost() + " / " + request.getHeader("user-agent");
                    
                    Feedback feedbackModel = new Feedback();
                    feedbackModel.connect();
                    feedbackModel.add(token, fbref, platform, receiver, referrer);
                    feedbackModel.disconnect();
                    
                    // !IMPORTANT - Make sure it is an OTP, remove a code after a job was finished
                    dbApis.removeFbOTP(code, token, fbref);

                    // force check a NULL callback
                    try{
                        if(callback.equals("SIGNAL"));
                    }catch(Exception e){
                        callback = "";
                    }
                    
                    // 200
                    if(callback.startsWith("jQuery"))
                        out.println(callback+"({"
                                + "\"status\":200,"
                                + "\"message\":\"Feedback acknowledged\""
                                + "})");
                    else
                        out.println("{"
                                + "\"status\":200,"
                                + "\"message\":\"Feedback acknowledged\""
                                + "}");
                }else{
                    // 401
                    out.println("{"
                                + "\"status\":401,"
                                + "\"message\":\"Unauthorized code, token, or fbref\""
                                + "}");
                }
            }else{
                // 500
                out.println("{"
                            + "\"status\":500,"
                            + "\"message\":\"Requires 3 params such code, token, and fbref\""
                            + "}");
            }
            
        } finally {            
            out.close();
            dbApis.disconnect();
        }
    }

    // <editor-fold defaultstate="collapsed" desc="HttpServlet methods. Click on the + sign on the left to edit the code.">
    /**
     * Handles the HTTP
     * <code>GET</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doGet(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Handles the HTTP
     * <code>POST</code> method.
     *
     * @param request servlet request
     * @param response servlet response
     * @throws ServletException if a servlet-specific error occurs
     * @throws IOException if an I/O error occurs
     */
    @Override
    protected void doPost(HttpServletRequest request, HttpServletResponse response)
            throws ServletException, IOException {
        processRequest(request, response);
    }

    /**
     * Returns a short description of the servlet.
     *
     * @return a String containing servlet description
     */
    @Override
    public String getServletInfo() {
        return "Short description";
    }// </editor-fold>
}
